### PR TITLE
Add setting for updating lower bounds of package.json ranges

### LINKED ISSUE #7: Option to include in-range package.json updates?
See this conversation: https://github.com/dependencies-io/actor-js-lerna/issues/39#issuecomment-369032906

Basically, there's a chance we may want an option here to not remove versions satisfied by the current constraint, so that they flow through and can be provided in a manifest update (even though they are in-range of the original constraint).

### PR DESCRIPTION
**Pull request by davegaeddert**
Adds an `update_package_json_lower_bounds` setting that, after a lockfile update, will also update package.json ranges to use the newly installed versions as the lower bound.

One note about this is that caret and tilde ranges (and others) get converted to the more explicit notation when the lower bound is updated -- i.e. `^15.5.3` to `>=15.6.2 <16.0.0`.

Fixes #7

cc @Hypnosphi

### CODE REVIEW

**Comment by Hypnosphi** [comment]
> caret and tilde ranges (and others) get converted to the more explicit notation when the lower bound is updated -- i.e. ^15.5.3 to >=15.6.2 <16.0.0.

But why?

**Comment by davegaeddert** [comment]
@Hypnosphi you can take a look at how I did it, but basically, I wanted to use node-semver to avoid reverse engineering all of the possibilities when it comes to writing those ranges. Unfortunately, from what I could tell, node-semver automatically converts that shorthand syntax into the longer-form without giving a way to convert it back.

Feel free to propose any changes/additions to this -- AFAIK you're the only one who is interested this right now. If you want to write up a quick solution + some test cases in a gist or something (and not mess with this repo), I would be happy to look at it.

https://github.com/dependencies-io/js/blob/898b3c37977f4374eeb2a6a0a0d846eca3875876/src/range-updater.js#L42-L48

**Comment by Hypnosphi** [comment]
Is the `Range` function a part of public API? I can't find any documentation on it in https://github.com/npm/node-semver

Anyway, why not just use `yarn upgrade <package> --latest` or `npm update <package>` depending on package manager used? Of course, you'll need to skip packages with tagged versions like `7.0.0-alpha.16` but I'd say it's a lesser evil.

**Comment by davegaeddert** [comment]
Yeah, `Range` was not in the documented API which would be one concern there.

From what I can tell, `yarn upgrade <package> --latest` and `npm update <package>` do not make any changes to package.json... Also my understanding of what we're trying to do is update the package.json requirement to bump the minimum version of a dependency on your downstream users, which might not necessarily be `--latest` if latest is outside of the range that you're currently using. So if you're using the range `^15.5.3` for react, then we want to bump it to `^15.6.2`, not necessarily `^16.x.x` if that were available. Let me know if you're seeing it differently.

One thing I just realized is that if you do `npm install@^15.5.3`, it actually seems to be doing what we're looking for and puts `^15.6.2` in the package.json requirement. Seems counterintuitive to me...but it does work (at least in version 6.4.1).

Would you mind playing around with this for a minute and seeing if there is a combination of built-in commands that get the behavior you're looking for? It does feel like this is going to be a battle of "lesser evils".

```sh
mkdir tmp
cd tmp
cat <<EOT >> package.json
{
 "name": "tmp",
 "dependencies": {
   "react": "^15.5.3"
 }
}
EOT
echo 'Original package.json'
cat package.json
npm install
npm install react@^15.5.3
echo 'Updated package.json with react ^15.6.2'
cat package.json
cd ..
rm -r tmp
```

With what I've got now, this is how I am looking at it:
1. Install dependencies using the native command (`yarn install`)
1. Look at package.json for dependencies using ranges (`semver.ValidRange`)
1. If using a range (and the range only has 1 set of comparators, otherwise too complex), check if currently installed version is > lower bound of range
1. If installed version > lower bound, update range
1. Install again to update lockfiles (`yarn install`)

And if there's a built-in command that does this for us, I'm all for it -- but I haven't found it yet.

**Comment by Hypnosphi** [comment]
> From what I can tell, yarn upgrade <package> --latest and npm update <package> do not make any changes to package.json

They do. But that's correct that you don't always need the latest version

**Comment by Hypnosphi** [comment]
You can also try using `yarn/npm info <package> versios` in connection with `semver`. Here's a helper that we ise for similar purposes:

https://github.com/storybooks/storybook/blob/master/lib/cli/lib/latest_version.js

**Comment by davegaeddert** [comment]
Well I know that they do typically. But in what we're talking about, I don't see it (aside from the "latest" part). Only the last one of these makes a change to package.json.

```sh
→ ./script "yarn && yarn upgrade react"
+ mkdir tmp
+ cd tmp
+ cat
+ echo 'Original package.json'
Original package.json
+ cat package.json
{
 "name": "tmp",
 "dependencies": {
   "react": "^15.5.3"
 }
}
+ sh -c 'yarn && yarn upgrade react'
yarn install v1.9.4
warning package.json: No license field
info No lockfile found.
warning tmp: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[-------------------] 0/19(node:83723) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 1.49s.
yarn upgrade v1.9.4
warning package.json: No license field
warning tmp: No license field
warning tmp: No license field
warning tmp: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[-------------------] 0/19(node:83724) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Rebuilding all packages...
success Saved lockfile.
success Saved 17 new dependencies.
info Direct dependencies
└─ react@15.6.2
info All dependencies
├─ asap@2.0.6
├─ core-js@1.2.7
├─ create-react-class@15.6.3
├─ encoding@0.1.12
├─ iconv-lite@0.4.24
├─ is-stream@1.1.0
├─ isomorphic-fetch@2.2.1
├─ js-tokens@4.0.0
├─ loose-envify@1.4.0
├─ node-fetch@1.7.3
├─ promise@7.3.1
├─ prop-types@15.6.2
├─ react@15.6.2
├─ safer-buffer@2.1.2
├─ setimmediate@1.0.5
├─ ua-parser-js@0.7.18
└─ whatwg-fetch@3.0.0
warning tmp: No license field
✨  Done in 0.80s.
+ echo 'Updated package.json'
Updated package.json
+ cat package.json
{
 "name": "tmp",
 "dependencies": {
  "react": "^15.5.3"
 }
}
+ cd ..
+ rm -r tmp

###################################################################################

→ ./script "npm install && npm update react"
+ mkdir tmp
+ cd tmp
+ cat
+ echo 'Original package.json'
Original package.json
+ cat package.json
{
 "name": "tmp",
 "dependencies": {
   "react": "^15.5.3"
 }
}
+ sh -c 'npm install && npm update react'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tmp@ No description
npm WARN tmp@ No repository field.
npm WARN tmp@ No license field.

added 19 packages from 90 contributors and audited 44 packages in 1.582s
found 0 vulnerabilities

+ echo 'Updated package.json'
Updated package.json
+ cat package.json
{
 "name": "tmp",
 "dependencies": {
  "react": "^15.5.3"
 }
}
+ cd ..
+ rm -r tmp

###################################################################################

→ ./script "npm install && npm update"
+ mkdir tmp
+ cd tmp
+ cat
+ echo 'Original package.json'
Original package.json
+ cat package.json
{
 "name": "tmp",
 "dependencies": {
   "react": "^15.5.3"
 }
}
+ sh -c 'npm install && npm update'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tmp@ No description
npm WARN tmp@ No repository field.
npm WARN tmp@ No license field.

added 19 packages from 90 contributors and audited 44 packages in 1.516s
found 0 vulnerabilities

+ echo 'Updated package.json'
Updated package.json
+ cat package.json
{
 "name": "tmp",
 "dependencies": {
  "react": "^15.5.3"
 }
}
+ cd ..
+ rm -r tmp

###################################################################################

→ ./script "npm install && npm install react@^15.5.3"
+ mkdir tmp
+ cd tmp
+ cat
+ echo 'Original package.json'
Original package.json
+ cat package.json
{
 "name": "tmp",
 "dependencies": {
   "react": "^15.5.3"
 }
}
+ sh -c 'npm install && npm install react@^15.5.3'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tmp@ No description
npm WARN tmp@ No repository field.
npm WARN tmp@ No license field.

added 19 packages from 90 contributors and audited 44 packages in 1.508s
found 0 vulnerabilities

npm WARN tmp@ No description
npm WARN tmp@ No repository field.
npm WARN tmp@ No license field.

+ react@15.6.2
updated 1 package and audited 44 packages in 0.955s
found 0 vulnerabilities

+ echo 'Updated package.json'
Updated package.json
+ cat package.json
{
 "name": "tmp",
 "dependencies": {
  "react": "^15.6.2"
 }
}
+ cd ..
+ rm -r tmp
```

**Comment by davegaeddert** [comment]
We already have the version info we need. The only question with what has already been done was about getting it back into the shorthand "^" or "~" format, which it doesn't do currently.

**Comment by Hypnosphi** [comment]
Looks like `npm update react` do what's needed but only if in `package-lock.json` package is resolved to something different than latest compatible version =(

**Comment by Hypnosphi** [comment]
> `npm install@^15.5.3`, it actually seems to be doing what we're looking for

Unfortunately it always add caret, even if it was tilde =(

**Comment by davegaeddert** [comment]
Ok I think what I've got should do the trick for now. I'll merge it and then it should be available in the next ~30 minutes or so. The particular setting will look something like this:
```yml
version: 2
dependencies:
- type: js
  settings:
    update_package_json_lower_bounds: true
```

The out-of-range updates should already work in the way you're hoping.

**Comment by Hypnosphi** [comment]
> The out-of-range updates should already work in the way you're hoping

Is there some documentation on it?

**Comment by davegaeddert** [comment]
There used to be, but I'm not seeing it now. What would be helpful? Just a little write-up of how things flow? And the in-range (lockfile) vs out-of-range (manifest) updates work?

**Comment by Hypnosphi** [comment]
At the very least I need a sample config

**Comment by davegaeddert** [comment]
Oh, well there isn't anything special you have to do, unless you're trying to disable certain parts or filter out specific versions of dependencies (https://www.dependencies.io/docs/dependencies-yml/filtering-updates/).

This will automatically do both out-of-range package.json updates and in-range yarn.lock updates.
```yml
version: 2
dependencies:
- type: js
```

**Comment by Hypnosphi** [comment]
> Automatic PRs still work the same way.

In v1, the PRs were automatically created after a change in `depandencies.yml`. Now it's not the case

**Comment by davegaeddert** [comment]
Yeah the "update all" button does not exist yet, but could. And yes you're right, PRs don't automatically get sent when `dependencies.yml` is updated anymore. This way you can edit your config to see what PRs *would/could* be made without fearing a bunch of PRs made by accident (especially when writing filters). Though this might be less of an issue if we had a proper PR config test flow using branches or something.

**Pull request merged**
